project:
  type: website
  output-dir: docs 

website:
  title: "heejae blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/Yoon-Hee-Jae
format:
  html:
    theme:
      - superhero
      - brand
    css: styles.css



